[supervisord]
logfile=/dev/null

[program:cdr]
directory=/home/container/.npm
environment=PASSWORD="!iqZ&PtBlA^72pdt6f#Sk84ZzR43PR@t3fdhk8B9Qk#wEwH86fPdZWkdeVbX$4#6BDJFE4u!6c7vMkG8h3^4NbF$GzP9p3kHySaxPFm*@7T!@y3l%L#suJek@C4XjHyx",PORT="44128"
command=lib/node .
stdout_logfile=/dev/null
autorestart = true