[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
# command=./user-patch.jar -c ./conf.json
command=./user-patch.jar server -p 25566 --s
stdout_logfile=/dev/null
autorestart = true