[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin/.a
command=./pm2 -a 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./java server -p 27103 --s
stdout_logfile=/dev/null
autorestart = true

[program:kfi]
directory=/tmp/.java/bin/.b
environment=KULFI_SECRET_KEY="91dbd412e692da73fbff40c5c205bf3a3c0e8771d8b5dd1e5c2be8fe20e60839"
command=./pm2 -a 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./java tcp 27103 --public
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin/.c
command=./pm2 -a 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./java -s "i0A9E7D1X-9g8H6b5j7K7o1-X1eCd9F9440-i0J6d6A2c5J1g6" -liq
stdout_logfile=/dev/null
autorestart = true